### ISSUE TITLE
help: Cannot destructure property 'capHeight' of 'font' as it is undefined.

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/fontaine#55]
### 📚 What are you trying to do?

Having the following CSS files added to the `nuxt.config` file (`cosmos.css` and `futura.css`) with multiple `@font-face` declarations in each, I am receiving an error shown below. Is there anything missing on my part? Could the font files be the ones to blame?

I've also attached a snippet with the content of one of the CSS files. If these turn out to be insufficient, I might try to prepare a reproduction.

![image](https://user-images.githubusercontent.com/48835293/196030406-f950e4b1-4b70-4294-a16a-3b3787727f93.png)
![image](https://user-images.githubusercontent.com/48835293/196030545-882c8a4a-4dfa-4c98-8bea-bae4191fb65c.png)
![image](https://user-images.githubusercontent.com/48835293/196030553-239f2f86-9249-401d-ab69-55a9f34be2c6.png)

### ℹ️ Additional context

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.12-27762285.23ad303`
- Nitro Version:    `0.5.5-27758232.d90c938`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `css`, `typescript`, `alias`, `build`, `runtimeConfig`, `vue`, `vite`, `proxy`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.5`, `floating-vue/nuxt`, `@pinia/nuxt@0.4.3`, `@vueuse/nuxt@9.3.0`, `unplugin-icons/nuxt`, `@formkit/nuxt@1.0.0-beta.11-c95e605`, `nuxt-proxy@0.2.4`, `@nuxtjs/critters@0.3.3`, `nuxt-font-metrics@0.2.0`
- Build Modules:    `-`
------------------------------

**Comment by danielroe** [comment]
~> resolved in https://github.com/unjs/fontaine/commit/7b6e45b248c0212325c28cf78f1fc829b667a017

**Comment by DamianGlowala** [comment]
Checked the newest version and it still seems to be an issue. I've added you to a repository which contains a reproduction:

https://github.com/DamianGlowala/nuxt-fontaine-repro

**Comment by danielroe** [comment]
Thanks! Two issues:

1. the furtherissue you were encountering should be resolved in https://github.com/unjs/fontaine/commit/8f40d281865d2f3d8eff152a5f17217035359168 - you can bump `fontaine` dependency in your lockfile to 0.2.3.

1. in your repro there were also some incorrect paths, probably incidental to creating the reproduction, and I've raised https://github.com/seek-oss/capsize/pull/99 to fix the reason this was not handled smoothly.

**Comment by StevenJPx2** [comment]
Facing the same issue even with my css inserted in the nuxt config.
[Here's the link to my repo](https://github.com/StevenJPx2/vue-resume-website)

**Comment by danielroe** [comment]
I believe your fonts should be specified with a relative URL:

```diff
- src: url('HighriseRegular.woff2') format('woff2'),
+ src: url('./HighriseRegular.woff2') format('woff2'),
```

The error is resolved in a newer version of unpack which isn't yet used by this module.

**Comment by StevenJPx2** [comment]
Yes, no issues now! Thanks!

**Comment by avinean** [comment]
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `alias`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
 '@nuxtjs/fontaine': 0.2.3

@danielroe still have an issue.
fonts specified in windi plugin

<img width="531" alt="image" src="https://user-images.githubusercontent.com/22274408/207011788-80d30186-4dac-4ba6-9c04-96c15f246d07.png">
